### ISSUE TITLE
Dynamic listings for "New Quest Subscription"

### ISSUE THREAD

**Issue by thermoscookies** [versx/WhMgr-UI#27]
for WhMgr-UI, had a user ask if active quest rewards in the database could be listed for  "New Quest Subscription" rather than having to type in the reward. Something similar to how pmsf shows only active quests

**Comment by versx** [comment]
Willing to add this no problem, the *only* issue I have with it is that I have to add _back_ the scanner database config section, which would be another breaking config change. Not a huge issue since I like breaking all the things anyways but worth noting.

Also for users with 20k+ pokestops looping all and parsing the reward message will definitely hit performance a little bit in the request but I'll try to minimize it as much as I can.

**Comment by thermoscookies** [comment]
using DISTINCT should help with that, no?

I believe this is the statement from PMSF: https://github.com/pmsf/PMSF/blob/a60813dac7d15f93a97cffeee69cd2b82f5d0744/lib/RDM.php#L879
`

**Comment by versx** [comment]
> using DISTINCT should help with that, no?
> 
> I believe this is the statement from PMSF: https://github.com/pmsf/PMSF/blob/a60813dac7d15f93a97cffeee69cd2b82f5d0744/lib/RDM.php#L879
> `

Awesome, thank you that should help for sure.
